### ISSUE TITLE
[Question] Locate SHA256 Hash

### ISSUE THREAD

**Issue by nyhtml** [utopia-team/IORegistryExplorer#1]
How do you look up the SHA256 hash for 3.0.2? I have access to older versions and want to look up the SHA256 hash for those as well.

**Comment by dreamwhite** [comment]
> How do you look up the SHA256 hash for 3.0.2? I have access to older versions and want to look up the SHA256 hash for those as well.

Hi, thanks a lot for giving help gathering old versions of IORegistryExplorer ^^ 

In order to get the SHA256 hash you simply need to fire up a terminal and run the following command:

`shasum -a 256 IORegistryExplorer.app`

(obv replace `IORegistryExplorer.app` with your path ._.)

**Comment by nyhtml** [comment]
Ah. So I can type ”shasum -a 256" and then drag the app to the terminal. I'll give it a go this morning. Thanks for the quick response.

**Comment by dreamwhite** [comment]
> Ah. So I can type ”shasum -a 256" and then drag the app to the terminal. I'll give it a go this morning. Thanks for the quick response.

Exactly ^^
At the moment, the copy of IORegistryExplorer v2.1 that I have has the following shasum:

`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  IORegistryExplorer v2.1.app`

**Comment by dreamwhite** [comment]
@nyhtml I've successfully uploaded the copy of IORegistryExplorer v2.1 downloaded from @dortania. I like seeing them as a trusted source ^^
